---
- name: Exercise1a
  hosts: localhost
  gather_facts: False
  tasks:
    - name: include tasks
      ansible.builtin.include_tasks: subtask1.yml
      loop:
        - 192.168.1.1
        - 192.168.2.1
        - 192.168.3.1
        - 192.168.4.1
