---
- name: Ex3
  hosts: local
  #gather_facts: False
  vars:
    dallas_devices:
      rtr1:
        ip_addr: 10.10.10.1
        device_type: arista_eos
      rtr2:
        ip_addr:  10.10.20.1
        device_type: juniper_junos
      rtr3:
        ip_addr:  10.10.30.1
        device_type:  juniper_junos
  tasks:
    - name: Test_loop
      ansible.builtin.debug:
        msg:  "{{ item.key }} --> {{ item.vlaue['ip_addr'] }}"
      loop: "{{ dallas_devices | dict2items }}"
