---
- name: Print out inventory variables
  hosts: all
  gather_facts: False

  vars:
    dns1=8.8.8.8
    dns2=8.8.4.4

  tasks:
    - name: Print out ansible_host
      ansible.builtin.debug:
        var: ansible_host

    - name: Print out inventory_hostname
      ansible.builtin.debug:
        mgs:  |
          "DNS1: {{ dns1 }}"
          "DNS2: {{ dns2 }}"
